sudo: required
services:
  - docker
  
before_install:
  - docker build -t dtsuper3/docker-react -f Dockerfile.dev .

script:
  - docker run dtsuper3/docker-react npm run test -- --watchAll=false --coverage



